Check the results of all downstream jobs
Signed-off-by: Peter Nied <peternied@hotmail.com>

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -218,5 +218,8 @@ jobs:
     if: always()
     runs-on: ubuntu-latest
     steps:
+      - if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }}
+        run: |
+          echo "One or more job cancelled, failed, or skipped" && exit 1
       - run: |
           echo '## :heavy_check_mark: All continous integration checks pass' >> $GITHUB_STEP_SUMMARY
